[build]
  command = "npm install"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200